import os

import numpy as np

RANDOM_STATE = 42
TIME_LIMIT = 300

RESULTS_FOLDER = 'results'
AUX_DATA_FOLDER = "aux_data"
PROFILES_FOLDER = 'profiles'
PROFILES_PATH = os.path.join(AUX_DATA_FOLDER, PROFILES_FOLDER)

COMPLETE_SUBRESULTS_FOLDER = 'complete_subresults'
INCOMPLETE_SUBRESULTS_FOLDER = 'incomplete_subresults'
COMPLETE_SUBRESULTS_PATH = os.path.join(RESULTS_FOLDER, COMPLETE_SUBRESULTS_FOLDER)
INCOMPLETE_SUBRESULTS_PATH = os.path.join(RESULTS_FOLDER, INCOMPLETE_SUBRESULTS_FOLDER)


COMPLETE_RESULTS_FILE = 'complete_algorithms_evaluation.csv'
INCOMPLETE_RESULTS_FILE = 'incomplete_algorithms_evaluation.csv'
TIME_RESULTS_FILE = 'time_evaluation.csv'
DATASET_TABLE = "dataset_table.csv"
COMPLETE_RESULTS_PATH = os.path.join(RESULTS_FOLDER, COMPLETE_RESULTS_FILE)
INCOMPLETE_RESULTS_PATH = os.path.join(RESULTS_FOLDER, INCOMPLETE_RESULTS_FILE)
TIME_RESULTS_PATH = os.path.join(RESULTS_FOLDER, TIME_RESULTS_FILE)
DATASET_TABLE_PATH = os.path.join(AUX_DATA_FOLDER, DATASET_TABLE)

COMPLETE_LOGS_FILE = 'complete_logs.txt'
INCOMPLETE_LOGS_FILE = 'incomplete_logs.txt'
TIME_LOGS_FILE = 'time_logs.txt'
COMPLETE_LOGS_PATH = os.path.join(RESULTS_FOLDER, COMPLETE_LOGS_FILE)
INCOMPLETE_LOGS_PATH = os.path.join(RESULTS_FOLDER, INCOMPLETE_LOGS_FILE)
TIME_LOGS_PATH = os.path.join(RESULTS_FOLDER, TIME_LOGS_FILE)

COMPLETE_ERRORS_FILE = 'complete_errors.txt'
INCOMPLETE_ERRORS_FILE = 'incomplete_errors.txt'
TIME_ERRORS_FILE = 'time_errors.txt'
COMPLETE_ERRORS_PATH = os.path.join(RESULTS_FOLDER, COMPLETE_ERRORS_FILE)
INCOMPLETE_ERRORS_PATH = os.path.join(RESULTS_FOLDER, INCOMPLETE_ERRORS_FILE)
TIME_ERRORS_PATH = os.path.join(RESULTS_FOLDER, TIME_ERRORS_FILE)

amputation_mechanisms = ["EDM", 'MCAR', 'MAR', 'MNAR', "PM"]
probs = np.arange(100, step= 10)
imputation = [True, False]
runs_per_alg = np.arange(50)

